# Generated by Django 5.0.4 on 2024-06-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_at',
        ),
    ]
