# Generated by Django 5.0.4 on 2024-06-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_created_at_post_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
